name: Node.js CI/CD on Amazon Linux

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v2

      # Step 2: Install dependencies in the repo root
      - name: Install dependencies
        working-directory: ./  # adjust if package.json is in a subfolder
        run: npm install

      # Step 3: Deploy files to EC2
      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"               # repository root
          target: "/var/www/rekognition/rekognition"

      # Step 4: Restart PM2 application on EC2
      - name: Restart PM2 application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/rekognition/rekognition
            npm install               # ensure dependencies are installed on EC2
            pm2 reload ecosystem.config.js
